'''
BASICS , DATATYPES , COMMENTS
LISTS, DICTIONARYIES, TUPLES , SETS INTRODUCTION
'''

items = [] # TO DECLARE A LIST NAMED items

items.insert(0, 50) # TO INSERT 50 IN THE 0 TH INDEX OF THE LIST
items.insert(1, 43) # TO INSERT 43 IN THE 1 ST INDEX OF THE LIST
items.insert(2, 67) # TO INSERT 67 IN THE 2 ND INDEX OF THE LIST

set = set()

set.add(8) # TO ADD A VALUE TO THE SET

'''
CONVERSION BETWEEN DIFFERENT DATATYPES
int(), str() AND MORE
'''

'''

I HAVE ALREADY INSTALLED VS CODE AS A TEXT EDITOR AND ALSO HAVE PYTHON INSTALLED ALONG WITH IT
AND AS I DIDINT UNDERSTOOD AHT TO DO FOR TODAYS ASSIGNMENT SO I TYPED THIS AND UPLOADED AS ASSIGNMENT

'''